import type { Flight, Airline, PriceRange, StopOption, DepartureTimeOption } from "../../types/flight"

// Datos de muestra para los vuelos
export const mockFlights: Flight[] = [
  {
    id: "flight-1",
    airline: "Ali Airways",
    airlineLogo: "/images/logo/logo-2.svg",
    flightNumber: "AA1234",
    departureTime: "2023-12-15T08:30:00",
    arrivalTime: "2023-12-15T10:45:00",
    departureAirport: "MEX",
    arrivalAirport: "CUN",
    departureCity: "Ciudad de México",
    arrivalCity: "Cancún",
    price: 2499,
    taxes: 350,
    currency: "MXN",
    durationMinutes: 135,
    stops: 0,
    aircraft: "Boeing 737-800",
    availableSeats: 42,
  },
  {
    id: "flight-2",
    airline: "Ali Airways",
    airlineLogo: "/images/logo/logo-2.svg",
    flightNumber: "AA1456",
    departureTime: "2023-12-15T12:15:00",
    arrivalTime: "2023-12-15T14:30:00",
    departureAirport: "MEX",
    arrivalAirport: "CUN",
    departureCity: "Ciudad de México",
    arrivalCity: "Cancún",
    price: 2199,
    taxes: 320,
    currency: "MXN",
    durationMinutes: 135,
    stops: 0,
    aircraft: "Airbus A320",
    availableSeats: 28,
  },
  {
    id: "flight-3",
    airline: "Ali Airways",
    airlineLogo: "/images/logo/logo-2.svg",
    flightNumber: "AA1789",
    departureTime: "2023-12-15T16:45:00",
    arrivalTime: "2023-12-15T19:00:00",
    departureAirport: "MEX",
    arrivalAirport: "CUN",
    departureCity: "Ciudad de México",
    arrivalCity: "Cancún",
    price: 1899,
    taxes: 280,
    currency: "MXN",
    durationMinutes: 135,
    stops: 0,
    aircraft: "Boeing 737-800",
    availableSeats: 15,
  },
  {
    id: "flight-4",
    airline: "Ali Airways",
    airlineLogo: "/images/logo/logo-2.svg",
    flightNumber: "AA2345",
    departureTime: "2023-12-15T07:00:00",
    arrivalTime: "2023-12-15T10:30:00",
    departureAirport: "MEX",
    arrivalAirport: "CUN",
    departureCity: "Ciudad de México",
    arrivalCity: "Cancún",
    price: 2799,
    taxes: 390,
    currency: "MXN",
    durationMinutes: 210,
    stops: 1,
    aircraft: "Airbus A320",
    availableSeats: 32,
  },
  {
    id: "flight-5",
    airline: "Ali Airways",
    airlineLogo: "/images/logo/logo-2.svg",
    flightNumber: "AA3456",
    departureTime: "2023-12-15T14:30:00",
    arrivalTime: "2023-12-15T18:45:00",
    departureAirport: "MEX",
    arrivalAirport: "CUN",
    departureCity: "Ciudad de México",
    arrivalCity: "Cancún",
    price: 1799,
    taxes: 250,
    currency: "MXN",
    durationMinutes: 255,
    stops: 1,
    aircraft: "Boeing 737-700",
    availableSeats: 8,
  },
  {
    id: "flight-6",
    airline: "Ali Airways",
    airlineLogo: "/images/logo/logo-2.svg",
    flightNumber: "AA5678",
    departureTime: "2023-12-15T20:15:00",
    arrivalTime: "2023-12-15T22:30:00",
    departureAirport: "MEX",
    arrivalAirport: "CUN",
    departureCity: "Ciudad de México",
    arrivalCity: "Cancún",
    price: 2299,
    taxes: 330,
    currency: "MXN",
    durationMinutes: 135,
    stops: 0,
    aircraft: "Airbus A320",
    availableSeats: 22,
  },
]

// Datos de muestra para los filtros
export const mockAirlines: Airline[] = [
  { id: "ali-airways", name: "Ali Airways" },
  { id: "skyteam", name: "SkyTeam Alliance" },
  { id: "star-alliance", name: "Star Alliance" },
]

export const mockPriceRanges: PriceRange[] = [
  { id: "economy", name: "Económico", min: 0, max: 2000 },
  { id: "standard", name: "Estándar", min: 2000, max: 3000 },
  { id: "premium", name: "Premium", min: 3000, max: 5000 },
]

export const mockStops: StopOption[] = [
  { id: "direct", name: "Vuelo directo", value: 0 },
  { id: "one-stop", name: "1 escala", value: 1 },
  { id: "two-stops", name: "2 o más escalas", value: 2 },
]

export const mockDepartureTimes: DepartureTimeOption[] = [
  { id: "morning", name: "Mañana (6:00 - 12:00)", start: 6, end: 12 },
  { id: "afternoon", name: "Tarde (12:00 - 18:00)", start: 12, end: 18 },
  { id: "evening", name: "Noche (18:00 - 24:00)", start: 18, end: 24 },
]
