import type { ReservationWithFlight } from "@/types/reservation"

export const mockReservations: ReservationWithFlight[] = [
  {
    id: "res001",
    flightId: "flight001",
    passenger: {
      firstName: "Juan",
      lastName: "Pérez",
      email: "juan.perez@email.com",
      phone: "+52 55 1234 5678",
      documentType: "passport",
      documentNumber: "A12345678",
    },
    payment: {
      cardNumber: "**** **** **** 1234",
      cardHolder: "Juan Pérez",
      expiryDate: "12/25",
      cvv: "***",
    },
    totalPrice: 15500,
    currency: "MXN",
    status: "confirmed",
    createdAt: "2024-01-15T10:30:00Z",
    flight: {
      id: "flight001",
      airline: "Ali Airways",
      airlineLogo: "/images/logo/logo-2.svg",
      flightNumber: "AA-101",
      departureTime: "08:30",
      arrivalTime: "11:45",
      departureAirport: "MEX",
      arrivalAirport: "CUN",
      departureCity: "Ciudad de México",
      arrivalCity: "Cancún",
      durationMinutes: 195,
      price: 12500,
      taxes: 3000,
      currency: "MXN",
      aircraft: "Boeing 737-800",
      stops: 0,
      availableSeats: 45,
    },
  },
  {
    id: "res002",
    flightId: "flight002",
    passenger: {
      firstName: "María",
      lastName: "González",
      email: "maria.gonzalez@email.com",
      phone: "+52 55 9876 5432",
      documentType: "passport",
      documentNumber: "B87654321",
    },
    payment: {
      cardNumber: "**** **** **** 5678",
      cardHolder: "María González",
      expiryDate: "08/26",
      cvv: "***",
    },
    totalPrice: 18900,
    currency: "MXN",
    status: "confirmed",
    createdAt: "2024-01-20T14:15:00Z",
    flight: {
      id: "flight002",
      airline: "Ali Airways",
      airlineLogo: "/images/logo/logo-2.svg",
      flightNumber: "AA-205",
      departureTime: "14:20",
      arrivalTime: "16:10",
      departureAirport: "GDL",
      arrivalAirport: "MTY",
      departureCity: "Guadalajara",
      arrivalCity: "Monterrey",
      durationMinutes: 110,
      price: 15500,
      taxes: 3400,
      currency: "MXN",
      aircraft: "Airbus A320",
      stops: 0,
      availableSeats: 32,
    },
  },
]
